version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: yes # Ensures existing files are overwritten during deployment
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
