version: 0.2
phases:
  install:
    commands:
      - echo Installing... # Placeholder for any install commands (e.g., npm install)
  build:
    commands:
      - echo Building... # Placeholder for any build commands (e.g., npm run build)
      - mkdir -p output
      # Copy only the necessary files for deployment into the output directory
      - cp -r index.html css js assets appspec.yml scripts output/
artifacts:
  files:
    - output/**/* # Package everything within the output directory
  discard-paths: no # Keep the directory structure inside the artifact
