version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building application...
      - mkdir -p output
      - cp index.html script.js style.css buildspec.yml appspec.yml -t output/
      - cp -r images output/
      - cp -r scripts output/

artifacts:
  files:
    - output/**/*
